name: WhatsApp bot ⚡
on:
  push:
    branches:
      - master
    workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"
jobs:
  Learning-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Execute js script by KazeDevID
        run: node .
